'use client';

/**
 * ConversationalPrompts Component - SAAS_RENDER_ONLY + SAAS_EVENT_ONLY
 *
 * Renders conversational prompts from OS and emits user responses.
 *
 * ARCHITECTURE COMPLIANCE:
 * - SaaS ONLY renders prompts generated by OS/SIVA
 * - SaaS NEVER generates or phrases prompts
 * - SaaS emits user intent events to OS
 * - OS decides when to show prompts
 * - SIVA generates prompt text (stateless)
 *
 * Architecture: OS decides. SIVA reasons. SaaS renders.
 */

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

interface ConversationalPrompt {
  id: string;
  type: 'AFTER_BATCH' | 'AFTER_LIKE' | 'AFTER_DISLIKE' | 'LOW_MATCHES' | 'REFINEMENT';
  text: string;
  options?: Array<{
    label: string;
    value: string;
    action: string;
  }>;
  allowFreeform?: boolean;
  placeholder?: string;
}

interface ConversationalPromptsProps {
  /** Current prompt from OS (null = no prompt to show) */
  prompt: ConversationalPrompt | null;
  /** Emit user response to OS */
  onResponse: (promptId: string, response: { action: string; value?: string }) => void;
  /** Dismiss prompt */
  onDismiss: (promptId: string) => void;
  /** Loading state */
  isLoading?: boolean;
}

export function ConversationalPrompts({
  prompt,
  onResponse,
  onDismiss,
  isLoading = false,
}: ConversationalPromptsProps) {
  const [freeformInput, setFreeformInput] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);

  if (!prompt) return null;

  const handleOptionClick = async (option: { action: string; value?: string }) => {
    setIsSubmitting(true);
    try {
      // SAAS_EVENT_ONLY: Emit user intent to OS
      await onResponse(prompt.id, option);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleFreeformSubmit = async () => {
    if (!freeformInput.trim()) return;

    setIsSubmitting(true);
    try {
      // SAAS_EVENT_ONLY: Emit freeform input to OS for parsing
      await onResponse(prompt.id, {
        action: 'FREEFORM',
        value: freeformInput.trim(),
      });
      setFreeformInput('');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0, y: 20, scale: 0.95 }}
        animate={{ opacity: 1, y: 0, scale: 1 }}
        exit={{ opacity: 0, y: -20, scale: 0.95 }}
        className="bg-gradient-to-r from-blue-50 to-indigo-50 dark:from-blue-900/20 dark:to-indigo-900/20 rounded-xl border border-blue-200 dark:border-blue-800 p-4 shadow-sm"
      >
        {/* Header */}
        <div className="flex items-start justify-between mb-3">
          <div className="flex items-center gap-2">
            <span className="text-xl">{getPromptIcon(prompt.type)}</span>
            <span className="text-xs font-medium text-blue-600 dark:text-blue-400 uppercase tracking-wide">
              SIVA
            </span>
          </div>
          <button
            onClick={() => onDismiss(prompt.id)}
            className="p-1 text-gray-400 hover:text-gray-600 transition-colors"
            title="Dismiss"
          >
            ✕
          </button>
        </div>

        {/* Prompt Text - SAAS_RENDER_ONLY from OS/SIVA */}
        <p className="text-gray-800 dark:text-gray-200 font-medium mb-4">
          {prompt.text}
        </p>

        {/* Quick Response Options - SAAS_RENDER_ONLY */}
        {prompt.options && prompt.options.length > 0 && (
          <div className="flex flex-wrap gap-2 mb-3">
            {prompt.options.map((option, idx) => (
              <button
                key={idx}
                onClick={() => handleOptionClick(option)}
                disabled={isSubmitting || isLoading}
                className="px-4 py-2 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg text-sm font-medium text-gray-700 dark:text-gray-300 hover:border-blue-400 hover:text-blue-600 transition-colors disabled:opacity-50"
              >
                {option.label}
              </button>
            ))}
          </div>
        )}

        {/* Freeform Input - SAAS_EVENT_ONLY */}
        {prompt.allowFreeform && (
          <div className="flex gap-2">
            <input
              type="text"
              value={freeformInput}
              onChange={(e) => setFreeformInput(e.target.value)}
              placeholder={prompt.placeholder || 'Type your preference...'}
              disabled={isSubmitting || isLoading}
              onKeyDown={(e) => {
                if (e.key === 'Enter' && !e.shiftKey) {
                  e.preventDefault();
                  handleFreeformSubmit();
                }
              }}
              className="flex-1 px-3 py-2 border border-gray-200 dark:border-gray-700 rounded-lg text-sm bg-white dark:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:opacity-50"
            />
            <button
              onClick={handleFreeformSubmit}
              disabled={!freeformInput.trim() || isSubmitting || isLoading}
              className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isSubmitting ? '...' : 'Send'}
            </button>
          </div>
        )}
      </motion.div>
    </AnimatePresence>
  );
}

function getPromptIcon(type: ConversationalPrompt['type']): string {
  switch (type) {
    case 'AFTER_LIKE':
      return '👍';
    case 'AFTER_DISLIKE':
      return '🎯';
    case 'AFTER_BATCH':
      return '💡';
    case 'LOW_MATCHES':
      return '🔍';
    case 'REFINEMENT':
      return '✨';
    default:
      return '💬';
  }
}

/**
 * SIVACommentary Component - SAAS_RENDER_ONLY
 *
 * Renders SIVA's commentary on lead results.
 * Commentary is generated by SIVA (reasoning) based on OS-provided context.
 */
interface SIVACommentaryProps {
  /** Commentary text from OS/SIVA */
  commentary: string | null;
  /** Whether commentary is loading */
  isLoading?: boolean;
}

export function SIVACommentary({ commentary, isLoading = false }: SIVACommentaryProps) {
  if (isLoading) {
    return (
      <div className="flex items-center gap-2 p-3 bg-gray-50 dark:bg-gray-800 rounded-lg">
        <span className="animate-pulse">💭</span>
        <div className="flex-1">
          <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded animate-pulse w-3/4"></div>
        </div>
      </div>
    );
  }

  if (!commentary) return null;

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className="flex items-start gap-2 p-3 bg-gradient-to-r from-purple-50 to-blue-50 dark:from-purple-900/20 dark:to-blue-900/20 rounded-lg border border-purple-100 dark:border-purple-800"
    >
      <span className="text-lg flex-shrink-0">💬</span>
      <div>
        <span className="text-xs font-medium text-purple-600 dark:text-purple-400 uppercase tracking-wide">
          SIVA
        </span>
        <p className="text-sm text-gray-700 dark:text-gray-300 mt-0.5">
          {commentary}
        </p>
      </div>
    </motion.div>
  );
}

/**
 * RefinementInput Component - SAAS_EVENT_ONLY
 *
 * Natural language refinement input.
 * Emits raw text to OS, which uses SIVA to parse intent.
 */
interface RefinementInputProps {
  /** Emit refinement text to OS */
  onSubmit: (text: string) => void;
  /** Placeholder text */
  placeholder?: string;
  /** Loading state */
  isLoading?: boolean;
  /** Example refinements to show */
  examples?: string[];
}

export function RefinementInput({
  onSubmit,
  placeholder = 'Refine your search (e.g., "Show only 100+ employees")...',
  isLoading = false,
  examples = [],
}: RefinementInputProps) {
  const [input, setInput] = useState('');

  const handleSubmit = () => {
    if (!input.trim() || isLoading) return;
    // SAAS_EVENT_ONLY: Emit raw text, OS/SIVA parses
    onSubmit(input.trim());
    setInput('');
  };

  return (
    <div className="space-y-2">
      <div className="flex gap-2">
        <input
          type="text"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder={placeholder}
          disabled={isLoading}
          onKeyDown={(e) => {
            if (e.key === 'Enter' && !e.shiftKey) {
              e.preventDefault();
              handleSubmit();
            }
          }}
          className="flex-1 px-4 py-2.5 border border-gray-200 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:opacity-50"
        />
        <button
          onClick={handleSubmit}
          disabled={!input.trim() || isLoading}
          className="px-4 py-2.5 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isLoading ? (
            <span className="animate-spin">⏳</span>
          ) : (
            'Refine'
          )}
        </button>
      </div>

      {/* Quick Examples */}
      {examples.length > 0 && (
        <div className="flex flex-wrap gap-1.5">
          <span className="text-xs text-gray-500">Try:</span>
          {examples.map((example, idx) => (
            <button
              key={idx}
              onClick={() => setInput(example)}
              className="text-xs px-2 py-1 bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400 rounded hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors"
            >
              {example}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

export default ConversationalPrompts;
