'use client';

/**
 * AIGeneratedBadge Component
 * VS7: AI-UX Polishing
 *
 * Badge that indicates content was generated by SIVA AI.
 * Authorization Code: VS1-VS9-APPROVED-20251213
 */

import { motion } from 'framer-motion';

interface AIGeneratedBadgeProps {
  model?: string;
  timestamp?: string;
  variant?: 'default' | 'minimal' | 'detailed';
  className?: string;
}

export function AIGeneratedBadge({
  model,
  timestamp,
  variant = 'default',
  className = '',
}: AIGeneratedBadgeProps) {
  if (variant === 'minimal') {
    return (
      <span className={`inline-flex items-center gap-1 text-xs text-gray-400 ${className}`}>
        <span className="text-purple-400">✨</span> AI
      </span>
    );
  }

  if (variant === 'detailed') {
    return (
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        className={`inline-flex items-center gap-2 px-3 py-1.5 bg-gradient-to-r from-purple-50 to-blue-50 dark:from-purple-900/20 dark:to-blue-900/20 rounded-full border border-purple-100 dark:border-purple-800 ${className}`}
      >
        <span className="text-sm">🧠</span>
        <div className="flex flex-col">
          <span className="text-xs font-medium text-purple-700 dark:text-purple-400">
            Generated by SIVA
          </span>
          {model && (
            <span className="text-[10px] text-gray-500 dark:text-gray-400">
              Model: {model}
            </span>
          )}
          {timestamp && (
            <span className="text-[10px] text-gray-500 dark:text-gray-400">
              {new Date(timestamp).toLocaleString()}
            </span>
          )}
        </div>
      </motion.div>
    );
  }

  // Default variant
  return (
    <motion.span
      initial={{ opacity: 0, scale: 0.9 }}
      animate={{ opacity: 1, scale: 1 }}
      className={`inline-flex items-center gap-1.5 px-2 py-0.5 bg-gradient-to-r from-purple-100 to-blue-100 dark:from-purple-900/30 dark:to-blue-900/30 text-purple-700 dark:text-purple-400 rounded-full text-xs font-medium ${className}`}
    >
      <span>✨</span>
      <span>AI Generated</span>
    </motion.span>
  );
}

export default AIGeneratedBadge;
